<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-69CS28LU" failures="1" tests="5" name="Listener Test Case" time="0.068" errors="0" timestamp="2022-07-20T17:20:06 IST">
  <testcase classname="com.testng.listeners.SampleTestClass" name="testFour" time="0.014">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.002"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testOne" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testThree" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestClass.testThree(SampleTestClass.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
